### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by bevacqua** [oneshot/buenosaires#2]
We need collaborators to help run this event. Register your interest here.

**Comment by bevacqua** [comment]
@banode

**Comment by bevacqua** [comment]
@banodejs any takers? :wink:

**Comment by bevacqua** [comment]
@banodejs/owners

**Comment by bevacqua** [comment]
@eafelix @nescalante @jaclar @a0viedo @pazguille any takers? :rocket:

**Comment by nescalante** [comment]
Más detalles por favor

**Comment by jaclar** [comment]
@nescalante contexto: http://oneshot.nodeconf.com/

@bevacqua como puedo ayudar

**Comment by a0viedo** [comment]
@jaclar haciendo una proposal para una charla :smiley:

**Comment by bevacqua** [comment]
@jaclar Primero que nada, deberíamos conseguir sponsors para ver cuanto nos podemos estirar con el budget #5 al buscar un venue (con cuanta capacidad, como bien preguntó @a0viedo?), traer speakers de afuera, etc. Sería cuestión de contactarlos, según recuerdo hay un ejemplo del mail que se puede usar en algún repo de nodeschool

**Comment by eafelix** [comment]
Eso lo podemos gestionar, @jaclar @bevacqua van a frontendba? podemos discutir esto alli junto con los chicos para armar algo mas grande

**Comment by bevacqua** [comment]
No creo, pero voy a @banode
